package net.homeip.mleclerc.omnilink.enumeration;

@SuppressWarnings("serial")
public class UnitControlEnum extends Enum
{
    public final static EnumInfo metaInfo = new EnumInfo();

    public final static UnitControlEnum OFF = new UnitControlEnum("Off", 0);
    public final static UnitControlEnum ON = new UnitControlEnum("On", 1);
    public final static UnitControlEnum DIM_1 = new UnitControlEnum("Dim 1", 17);
    public final static UnitControlEnum DIM_2 = new UnitControlEnum("Dim 2", 18);
    public final static UnitControlEnum DIM_3 = new UnitControlEnum("Dim 3", 19);
    public final static UnitControlEnum DIM_4 = new UnitControlEnum("Dim 4", 20);
    public final static UnitControlEnum DIM_5 = new UnitControlEnum("Dim 5", 21);
    public final static UnitControlEnum DIM_6 = new UnitControlEnum("Dim 6", 22);
    public final static UnitControlEnum DIM_7 = new UnitControlEnum("Dim 7", 23);
    public final static UnitControlEnum DIM_8 = new UnitControlEnum("Dim 8", 24);
    public final static UnitControlEnum DIM_9 = new UnitControlEnum("Dim 9", 25);
    public final static UnitControlEnum BRIGHT_1 = new UnitControlEnum("Bright 1", 33);
    public final static UnitControlEnum BRIGHT_2 = new UnitControlEnum("Bright 2", 34);
    public final static UnitControlEnum BRIGHT_3 = new UnitControlEnum("Bright 3", 35);
    public final static UnitControlEnum BRIGHT_4 = new UnitControlEnum("Bright 4", 36);
    public final static UnitControlEnum BRIGHT_5 = new UnitControlEnum("Bright 5", 37);
    public final static UnitControlEnum BRIGHT_6 = new UnitControlEnum("Bright 6", 38);
    public final static UnitControlEnum BRIGHT_7 = new UnitControlEnum("Bright 7", 39);
    public final static UnitControlEnum BRIGHT_8 = new UnitControlEnum("Bright 8", 40);
    public final static UnitControlEnum BRIGHT_9 = new UnitControlEnum("Bright 9", 41);
    public final static UnitControlEnum LEVEL_0 = new UnitControlEnum("Level 0", 100);
    public final static UnitControlEnum LEVEL_1 = new UnitControlEnum("Level 1", 101);
    public final static UnitControlEnum LEVEL_2 = new UnitControlEnum("Level 2", 102);
    public final static UnitControlEnum LEVEL_3 = new UnitControlEnum("Level 3", 103);
    public final static UnitControlEnum LEVEL_4 = new UnitControlEnum("Level 4", 104);
    public final static UnitControlEnum LEVEL_5 = new UnitControlEnum("Level 5", 105);
    public final static UnitControlEnum LEVEL_6 = new UnitControlEnum("Level 6", 106);
    public final static UnitControlEnum LEVEL_7 = new UnitControlEnum("Level 7", 107);
    public final static UnitControlEnum LEVEL_8 = new UnitControlEnum("Level 8", 108);
    public final static UnitControlEnum LEVEL_9 = new UnitControlEnum("Level 9", 109);
    public final static UnitControlEnum LEVEL_10 = new UnitControlEnum("Level 10", 110);
    public final static UnitControlEnum LEVEL_11 = new UnitControlEnum("Level 11", 111);
    public final static UnitControlEnum LEVEL_12 = new UnitControlEnum("Level 12", 112);
    public final static UnitControlEnum LEVEL_13 = new UnitControlEnum("Level 13", 113);
    public final static UnitControlEnum LEVEL_14 = new UnitControlEnum("Level 14", 114);
    public final static UnitControlEnum LEVEL_15 = new UnitControlEnum("Level 15", 115);
    public final static UnitControlEnum LEVEL_16 = new UnitControlEnum("Level 16", 116);
    public final static UnitControlEnum LEVEL_17 = new UnitControlEnum("Level 17", 117);
    public final static UnitControlEnum LEVEL_18 = new UnitControlEnum("Level 18", 118);
    public final static UnitControlEnum LEVEL_19 = new UnitControlEnum("Level 19", 119);
    public final static UnitControlEnum LEVEL_20 = new UnitControlEnum("Level 20", 120);
    public final static UnitControlEnum LEVEL_21 = new UnitControlEnum("Level 21", 121);
    public final static UnitControlEnum LEVEL_22 = new UnitControlEnum("Level 22", 122);
    public final static UnitControlEnum LEVEL_23 = new UnitControlEnum("Level 23", 123);
    public final static UnitControlEnum LEVEL_24 = new UnitControlEnum("Level 24", 124);
    public final static UnitControlEnum LEVEL_25 = new UnitControlEnum("Level 25", 125);
    public final static UnitControlEnum LEVEL_26 = new UnitControlEnum("Level 26", 126);
    public final static UnitControlEnum LEVEL_27 = new UnitControlEnum("Level 27", 127);
    public final static UnitControlEnum LEVEL_28 = new UnitControlEnum("Level 28", 128);
    public final static UnitControlEnum LEVEL_29 = new UnitControlEnum("Level 29", 129);
    public final static UnitControlEnum LEVEL_30 = new UnitControlEnum("Level 30", 130);
    public final static UnitControlEnum LEVEL_31 = new UnitControlEnum("Level 31", 131);
    public final static UnitControlEnum LEVEL_32 = new UnitControlEnum("Level 32", 132);
    public final static UnitControlEnum LEVEL_33 = new UnitControlEnum("Level 33", 133);
    public final static UnitControlEnum LEVEL_34 = new UnitControlEnum("Level 34", 134);
    public final static UnitControlEnum LEVEL_35 = new UnitControlEnum("Level 35", 135);
    public final static UnitControlEnum LEVEL_36 = new UnitControlEnum("Level 36", 136);
    public final static UnitControlEnum LEVEL_37 = new UnitControlEnum("Level 37", 137);
    public final static UnitControlEnum LEVEL_38 = new UnitControlEnum("Level 38", 138);
    public final static UnitControlEnum LEVEL_39 = new UnitControlEnum("Level 39", 139);
    public final static UnitControlEnum LEVEL_40 = new UnitControlEnum("Level 40", 140);
    public final static UnitControlEnum LEVEL_41 = new UnitControlEnum("Level 41", 141);
    public final static UnitControlEnum LEVEL_42 = new UnitControlEnum("Level 42", 142);
    public final static UnitControlEnum LEVEL_43 = new UnitControlEnum("Level 43", 143);
    public final static UnitControlEnum LEVEL_44 = new UnitControlEnum("Level 44", 144);
    public final static UnitControlEnum LEVEL_45 = new UnitControlEnum("Level 45", 145);
    public final static UnitControlEnum LEVEL_46 = new UnitControlEnum("Level 46", 146);
    public final static UnitControlEnum LEVEL_47 = new UnitControlEnum("Level 47", 147);
    public final static UnitControlEnum LEVEL_48 = new UnitControlEnum("Level 48", 148);
    public final static UnitControlEnum LEVEL_49 = new UnitControlEnum("Level 49", 149);
    public final static UnitControlEnum LEVEL_50 = new UnitControlEnum("Level 50", 150);
    public final static UnitControlEnum LEVEL_51 = new UnitControlEnum("Level 51", 151);
    public final static UnitControlEnum LEVEL_52 = new UnitControlEnum("Level 52", 152);
    public final static UnitControlEnum LEVEL_53 = new UnitControlEnum("Level 53", 153);
    public final static UnitControlEnum LEVEL_54 = new UnitControlEnum("Level 54", 154);
    public final static UnitControlEnum LEVEL_55 = new UnitControlEnum("Level 55", 155);
    public final static UnitControlEnum LEVEL_56 = new UnitControlEnum("Level 56", 156);
    public final static UnitControlEnum LEVEL_57 = new UnitControlEnum("Level 57", 157);
    public final static UnitControlEnum LEVEL_58 = new UnitControlEnum("Level 58", 158);
    public final static UnitControlEnum LEVEL_59 = new UnitControlEnum("Level 59", 159);
    public final static UnitControlEnum LEVEL_60 = new UnitControlEnum("Level 60", 160);
    public final static UnitControlEnum LEVEL_61 = new UnitControlEnum("Level 61", 161);
    public final static UnitControlEnum LEVEL_62 = new UnitControlEnum("Level 62", 162);
    public final static UnitControlEnum LEVEL_63 = new UnitControlEnum("Level 63", 163);
    public final static UnitControlEnum LEVEL_64 = new UnitControlEnum("Level 64", 164);
    public final static UnitControlEnum LEVEL_65 = new UnitControlEnum("Level 65", 165);
    public final static UnitControlEnum LEVEL_66 = new UnitControlEnum("Level 66", 166);
    public final static UnitControlEnum LEVEL_67 = new UnitControlEnum("Level 67", 167);
    public final static UnitControlEnum LEVEL_68 = new UnitControlEnum("Level 68", 168);
    public final static UnitControlEnum LEVEL_69 = new UnitControlEnum("Level 69", 169);
    public final static UnitControlEnum LEVEL_70 = new UnitControlEnum("Level 70", 170);
    public final static UnitControlEnum LEVEL_71 = new UnitControlEnum("Level 71", 171);
    public final static UnitControlEnum LEVEL_72 = new UnitControlEnum("Level 72", 172);
    public final static UnitControlEnum LEVEL_73 = new UnitControlEnum("Level 73", 173);
    public final static UnitControlEnum LEVEL_74 = new UnitControlEnum("Level 74", 174);
    public final static UnitControlEnum LEVEL_75 = new UnitControlEnum("Level 75", 175);
    public final static UnitControlEnum LEVEL_76 = new UnitControlEnum("Level 76", 176);
    public final static UnitControlEnum LEVEL_77 = new UnitControlEnum("Level 77", 177);
    public final static UnitControlEnum LEVEL_78 = new UnitControlEnum("Level 78", 178);
    public final static UnitControlEnum LEVEL_79 = new UnitControlEnum("Level 79", 179);
    public final static UnitControlEnum LEVEL_80 = new UnitControlEnum("Level 80", 180);
    public final static UnitControlEnum LEVEL_81 = new UnitControlEnum("Level 81", 181);
    public final static UnitControlEnum LEVEL_82 = new UnitControlEnum("Level 82", 182);
    public final static UnitControlEnum LEVEL_83 = new UnitControlEnum("Level 83", 183);
    public final static UnitControlEnum LEVEL_84 = new UnitControlEnum("Level 84", 184);
    public final static UnitControlEnum LEVEL_85 = new UnitControlEnum("Level 85", 185);
    public final static UnitControlEnum LEVEL_86 = new UnitControlEnum("Level 86", 186);
    public final static UnitControlEnum LEVEL_87 = new UnitControlEnum("Level 87", 187);
    public final static UnitControlEnum LEVEL_88 = new UnitControlEnum("Level 88", 188);
    public final static UnitControlEnum LEVEL_89 = new UnitControlEnum("Level 89", 189);
    public final static UnitControlEnum LEVEL_90 = new UnitControlEnum("Level 90", 190);
    public final static UnitControlEnum LEVEL_91 = new UnitControlEnum("Level 91", 191);
    public final static UnitControlEnum LEVEL_92 = new UnitControlEnum("Level 92", 192);
    public final static UnitControlEnum LEVEL_93 = new UnitControlEnum("Level 93", 193);
    public final static UnitControlEnum LEVEL_94 = new UnitControlEnum("Level 94", 194);
    public final static UnitControlEnum LEVEL_95 = new UnitControlEnum("Level 95", 195);
    public final static UnitControlEnum LEVEL_96 = new UnitControlEnum("Level 96", 196);
    public final static UnitControlEnum LEVEL_97 = new UnitControlEnum("Level 97", 197);
    public final static UnitControlEnum LEVEL_98 = new UnitControlEnum("Level 98", 198);
    public final static UnitControlEnum LEVEL_99 = new UnitControlEnum("Level 99", 199);
    public final static UnitControlEnum LEVEL_100 = new UnitControlEnum("Level 100", 200);

    public UnitControlEnum(String userLabel, int value)
    {
        super(userLabel, value);
        metaInfo.add(this);
    }
}
